# Generated by Django 3.0.7 on 2021-08-10 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='School_T',
            fields=[
                ('schoolID', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('schoolName', models.CharField(max_length=30)),
            ],
        ),
    ]
