# Generated by Django 3.0.7 on 2021-09-12 02:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Orders_T',
        ),
    ]
