# Generated by Django 3.0.7 on 2021-08-11 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order_T',
            fields=[
                ('orderID', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('customerName', models.CharField(max_length=30)),
            ],
        ),
        migrations.DeleteModel(
            name='School_T',
        ),
    ]
