# Generated by Django 3.0.7 on 2021-09-10 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20210811_0815'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customerName', models.CharField(max_length=30)),
                ('customerMessage', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='Order_T',
        ),
    ]
