# Generated by Django 3.0.7 on 2021-09-12 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_delete_orders_t'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders_T',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=30)),
                ('lname', models.CharField(max_length=30)),
                ('number', models.IntegerField(max_length=30)),
                ('cusaddress', models.CharField(max_length=50)),
                ('delins', models.CharField(max_length=60)),
            ],
        ),
    ]
