# Generated by Django 3.0.7 on 2021-09-10 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20210910_2111'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ContactUs',
            new_name='ContactUs_T',
        ),
    ]
