# Generated by Django 3.0.7 on 2021-09-12 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_orders_t_itemsordered'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders_t',
            name='totalCost',
            field=models.CharField(default=0, max_length=30),
        ),
    ]
