# Generated by Django 3.0.7 on 2021-09-13 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20210912_0914'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders_t',
            name='itemsOrdered',
            field=models.CharField(default=0, max_length=80),
        ),
        migrations.AlterField(
            model_name='orders_t',
            name='totalCost',
            field=models.CharField(default=0, max_length=80),
        ),
    ]
