# Generated by Django 3.0.7 on 2021-09-13 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20210913_1044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders_t',
            name='totalCost',
            field=models.TextField(max_length=80),
        ),
    ]
