# Generated by Django 3.0.7 on 2021-09-13 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20210913_1045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders_t',
            name='totalCost',
            field=models.CharField(max_length=80),
        ),
    ]
