# Generated by Django 3.0.7 on 2021-09-13 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20210913_1047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders_t',
            name='itemsOrdered',
            field=models.TextField(max_length=80),
        ),
    ]
